### ISSUE TITLE
Parent/child relationships

### ISSUE THREAD

**Issue by abb1991** [ElinaIvanova/f1-3-c2p1-colmar-academy#2]
I notice you use a lot of parent/child relationships to determine your elements like this:

```
.logo p {
  text-transform: capitalize;
}

.logo strong {
  font-weight: 600;
  color: #27BABA;
}

.logo img {
  heigth: auto;
}

.desktop ul {
  height: 100%;
  margin-right: 1.5rem;
  display: flex;
  justify-content: space-between;
  
```

While this is an effective strategy and a good use of a new concept, can you defend why you'd want to style your element this way rather than through a direct class/id?

**Comment by ElinaIvanova** [comment]
I know that there are different ways to name classes (e.g. BEM) and use selectors. Though the utilized way feels more natural and explicit to me, since one can always know what element one is currently styling and what properties can be applied to it. I can change this technique on direct classes if it's necessary, but is it?
